# baseURL = 'https://paulocv.github.io/episimu-dash2025/'
languageCode = 'en-us'
title = 'EpiSimu 2025'
theme = 'relearn'
[params]

  disableSearch = true

  # # Complete theme specification, with custom names
  [[params.themeVariant]]
      identifier = 'relearn-light'
      name = 'Light theme'
  # [[params.themeVariant]]
  #     identifier = 'relearn-dark'
  #     name = 'Dark theme'

  # # Simple theme specification
  # themeVariant = ["relearn-light", "relearn-dark", ]
